import '../styles/reset.css'
import '../styles/global.css'
import Header from '@/components/header/header'
import Footer from '@/components/footer/footer'

export const metadata = {
  title: 'NetFilms',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container">
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
